### ISSUE TITLE
AttributeError: 'HfDeepSpeedConfig' object has no attribute 'trainer_config_finalize

### ISSUE THREAD

**Issue by EternalSeer** [zjunlp/IEPile#12]
![ce90d0e5-f59e-42ae-a397-6cf1541599ef](https://github.com/zjunlp/IEPile/assets/166979630/db0eb0ce-8e21-4fb4-8e5b-c237e2a6a894)
baichuan和lama都报这个错，大佬求助

**Comment by guihonghao** [comment]
你是否使用的是qlora，即--bits 4

**Comment by guihonghao** [comment]
https://github.com/microsoft/DeepSpeed/issues/3733#issuecomment-1671891244

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by EternalSeer** [comment]
> [microsoft/DeepSpeed#3733 (comment)](https://github.com/microsoft/DeepSpeed/issues/3733#issuecomment-1671891244) 将--deepspeed configs/ds_config_bf16.json去掉，或者试试将deepspeed升级到0.10.0

使用的第一种方式，通了，多谢大佬

**Comment by EternalSeer** [comment]
> 请问您的问题是否已解决？

上面大佬给的方式，已解决
