### ISSUE TITLE
KeyError: 'response'

### ISSUE THREAD

**Issue by wuQi-666** [zjunlp/IEPile#13]
利用https://huggingface.co/datasets/zjunlp/InstructIE/tree/main/InstructIE-zh/InstructIE_%E5%8C%BB%E5%AD%A6
中的数据集在qwen1.5-14b-chat的lora微调模型的基础上继续训练，其中的运行代码.bash中的参数设置如下所示
![Snipaste_2024-05-06_17-06-01](https://github.com/zjunlp/IEPile/assets/139730426/7a205378-9e21-4be9-bb52-f43265ff1013)
运行报错如下所示
![image](https://github.com/zjunlp/IEPile/assets/139730426/d0999485-3788-48b4-8879-b8b0ce5547f7)
其中使用的数据集已经经过格式的转换

**Comment by guihonghao** [comment]
如果要将test集作为训练时的验证集，那么在处理test集时也应该使用 `--split train`，如下的命令转换数据格式。
```python
python ie2instruction/convert_func.py \
    --src_path data/NER/sample.json \
    --tgt_path data/NER/train.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \       
    --random_sort \
    --split train
```

**Comment by wuQi-666** [comment]
谢谢，问题已经解决，代码可以继续训练
