### ISSUE TITLE
EE-zh任务中DuIE-fin数据集疑问

### ISSUE THREAD

**Issue by pangpang-xuan** [zjunlp/IEPile#19]
<img width="774" alt="屏幕截图 2024-06-26 175817" src="https://github.com/zjunlp/IEPile/assets/142560164/0f27a6c1-f79f-49e9-b202-23684c0163d9">
为什么事件抽取的时候，对于相同事件类型，相同事件中元素组成进行了重复抽取？这样会影响模型的效果吗？
例子：DuIE-fin test.json 中第6997条数据
{
    "text": "网宿科技(300017.SZ)拟回购注销73.72万股限制性股票\n股市震荡，需要注意什么？\n跨年行情，应该如何布局？\n【立即开户，领取福利】",
    "event": [
        {
            "event_trigger": "回购",
            "event_type": "股份回购",
            "arguments": [
                {
                    "argument": "网宿科技",
                    "role": "回购方"
                }
            ]
        },
        {
            "event_trigger": "回购",
            "event_type": "股份回购",
            "arguments": [
                {
                    "argument": "网宿科技",
                    "role": "回购方"
                }
            ]
        }
    ],
    "task": "EE"
}

**Comment by guihonghao** [comment]
原始数据集中存在一定量的重复数据，可以过滤掉这部分重复数据再使用。

**Comment by pangpang-xuan** [comment]
> 原始数据集中存在一定量的重复数据，可以过滤掉这部分重复数据再使用。

好的谢谢您
