### ISSUE TITLE
llama3-8b lora报错

### ISSUE THREAD

**Issue by yip522364642** [zjunlp/IEPile#26]
运行代码：
output_dir='lora/Meta-Llama-3-8B-Instruct-PACK'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node=4 --master_port=1287 src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --model_name_or_path 'models/Meta-Llama-3-8B-Instruct' \
    --stage 'sft' \
    --model_name 'llama' \
    --template 'llama' \
    --train_file 'data/PACK/train.json' \
    --val_set_size 100 \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 8 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.1 \
    --optim "adamw_torch" \
    --max_source_length 300 \
    --cutoff_len 600 \
    --max_target_length 200 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.01 \
    --fp16 \
    --deepspeed configs/ds_config_fp16.json

报错信息：
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 166, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/ma-user/anaconda3/envs/PyTorch-2.0.0/lib/python3.9/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

**Comment by yip522364642** [comment]
感觉是llama3-8b模型的问题，我用baichuan2-7b能正常运行

**Comment by yip522364642** [comment]
二次训练也遇到同样的报错：

output_dir='lora/Meta-Llama-3-8B-Instruct-PACK'
mkdir -p ${output_dir}
CUDA_VISIBLE_DEVICES="0,1,2,3" torchrun --nproc_per_node=4 --master_port=1287 src/finetune.py \
    --do_train --do_eval \
    --overwrite_output_dir \
    --model_name_or_path "models/Meta-Llama-3-8B-Instruct" \
    --stage 'sft' \
    --model_name 'llama' \
    --template 'alpaca' \
    --train_file 'data/PACK/train.json' \
    --val_set_size 100 \
    --output_dir=${output_dir} \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 8 \
    --num_train_epochs 10 \
    --learning_rate 5e-5 \
    --max_grad_norm 0.1 \
    --optim "adamw_torch" \
    --max_source_length 300 \
    --cutoff_len 600 \
    --max_target_length 200 \
    --evaluation_strategy "epoch" \
    --save_strategy "epoch" \
    --save_total_limit 10 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.01 \
    --fp16 \
    --deepspeed configs/ds_config_fp16.json

**Comment by guihonghao** [comment]
可能模型问题，目前对llama3适配不是很好。

**Comment by zxlzr** [comment]
请问您还有其他问题吗
