### ISSUE TITLE
关于评测的一些疑问

### ISSUE THREAD

**Issue by rangehow** [zjunlp/IEPile#27]
您好，我想请问一下，论文里这几张大表怎么使用这个项目进行评估呢？是需要手动去下载数据适配成这个仓库支持的样子吗

![image](https://github.com/user-attachments/assets/b66638ee-85ee-4f9e-a199-0d99619ce7a1)

**Comment by guihonghao** [comment]
```
python ie2instruction/convert_func.py \
    --src_path data/NER/CoNLL2003/test.json \
    --tgt_path data/NER/CoNLL2003/test_converted.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \
    --split test
```
是这样的，需要修改语言language [zh、en]、任务task [NER RE EE]，推荐切分长度NER:6、RE、EE:4

**Comment by rangehow** [comment]
我们有一个批量处理的脚本/处理好的数据集吗，这样感觉不好对齐复现结果呀。
btw我用deepke的vllm示例（友情提醒这个readme和代码都有问题，readme里的脚本名字和仓库的都不一样，代码现在还属于不能直接跑的情况）跑了bosom，qwen2.5-7b-instruct生成的从我肉眼上看其实还行，但是因为生成的是类似
\```json
结果
\```
这样的东西，评测里没有尝试做一下json解析，所以最终得分是0分，让人有点纳闷。。。

**Comment by rangehow** [comment]
按照仓库里的做法，我处理了一下这个评测数据集，https://huggingface.co/datasets/JesusCrist/iepile_benchmark



> label 字段将用于后续评估。若输入数据中缺少标注字段（entity, relation, event），则转换后的测试数据将不包含label字段，适用于那些无原始标注数据的场景。

但是我发现有很多任务的数据里同时夹杂着label 为空/非空的情况(比如bc2gm），这是正常的情况吗？

**Comment by guihonghao** [comment]
> 我们有一个批量处理的脚本/处理好的数据集吗，这样感觉不好对齐复现结果呀。 btw我用deepke的vllm示例（友情提醒这个readme和代码都有问题，readme里的脚本名字和仓库的都不一样，代码现在还属于不能直接跑的情况）跑了bosom，qwen2.5-7b-instruct生成的从我肉眼上看其实还行，但是因为生成的是类似 ```json 结果 ``` 这样的东西，评测里没有尝试做一下json解析，所以最终得分是0分，让人有点纳闷。。。

已更新批量数据转换脚本 https://github.com/zjunlp/IEPile/blob/main/ie2instruction/eval_data_convert.bash

**Comment by zxlzr** [comment]
请问您还有其他问题吗
