### ISSUE TITLE
对于同一schema，在使用ie2instruction/convert_func.py生成数据时，训练数据与测试数据中schema的划分方式有差别。

### ISSUE THREAD

**Issue by syt1998** [zjunlp/IEPile#30]
例如，对于schema = [A, B, C, D, E, F, G, H]，在生成训练数据时，每条样本都按照同样的schema划分{[A, B, C, D], [E, F, G, H]}进行Batched Instruction Generation。而在生成测试数据时，每条样本都按照另一种schema划分{[H, B, G, D], [E, F, C, A]}进行Batched Instruction Generation。
请问，训练与推理的schema划分是否应该保持一致？如不需要保持一致，原因是什么呢？
谢谢。

**Comment by guihonghao** [comment]
这源自IEPile/ie2instruction/convert/processer/processer.py文件中从schema.json文件中加载schema时使用了set()保证每个schema不重复，但是也会导致每次生成数据时默认schema集顺序不一样。
但是这个并不影响，因为在生成训练数据时的--random_sort参数，会让每条数据的schema乱序，因此训练数据指令中的schema并不是一样的。不是全都是{[A, B, C, D], [E, F, G, H]}。

**Comment by guihonghao** [comment]
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/2d3b0896-e2f8-4bcf-be6d-003d6a7d6785">
可以看到NER的训练数据中指令里面的scheme顺序是不一样的

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by syt1998** [comment]
问题1：对于生成训练数据的脚本与生成测试数据的脚本，为什么生成训练数据的脚本中需要设置random_sort，而生成测试数据的脚本中不需要？

生成训练数据的脚本：
python ie2instruction/convert_func.py \
    --src_path data/NER/sample.json \
    --tgt_path data/NER/train.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \       
    --random_sort \
    --split train
    
生成测试数据的脚本：
python ie2instruction/convert_func.py \
    --src_path data/NER/sample.json \
    --tgt_path data/NER/test.json \
    --schema_path data/NER/schema.json \
    --language zh \
    --task NER \
    --split_num 6 \
    --split test
    
    
问题2：我在生成训练数据与生成测试数据时均未设置random_sort，请问以这样的数据在IEPILE上训练与推理是合理的吗？

**Comment by guihonghao** [comment]
问题1：生成测试数据的脚本中，可设置可不设置，顺序比较影响模型表现，[ABCD]和[BCDA]的顺序得到的结果可能不一样，设置为了保证稳定性。
问题2：我们已经修改了代码，把set改为了list，现在在未设置random_sort时，训练和测试在常规模式下的切分顺序应该一样。

**Comment by guihonghao** [comment]
<img width="626" alt="image" src="https://github.com/user-attachments/assets/12ddf11f-78cc-4d9e-b097-3f1f1797e76c">

**Comment by syt1998** [comment]
好的，我的这个问题已得到解答，谢谢。
