### ISSUE TITLE
对于不包含在IEPILE中的新的数据集，如何生成难负样本？

### ISSUE THREAD

**Issue by syt1998** [zjunlp/IEPile#31]
现有一个不包含在IEPILE中的医疗病例实体与关系抽取数据集，data/hard_negative/SPO_DuIE2.0.json与data/hard_negative/hard_dict.json中均无key可与新数据集中的大部分实体、关系标签相对应。
请问，对一个不包含在IEPILE中的新的数据集，如何自动构建一个字典，其中key为新数据集中的实体或关系标签，value为新数据集中与key代表的实体或关系标签容易混淆的实体或关系标签？是否需要自行构建这样一个字典？
谢谢。

**Comment by syt1998** [comment]
论文中并提及schema的聚类算法，github中也未找到聚类算法的实现，请问是需要自行设计一个算法或者手动构建字典吗？

**Comment by guihonghao** [comment]
没有算法，人工构建

**Comment by syt1998** [comment]
好的谢谢，我的疑问已得到解答。

**Comment by syt1998** [comment]
好的谢谢，我的疑问已经得到了解答。
