### ISSUE TITLE
如果要模型识别一条文本中可能出现的实体类型，instruction与output应该如何设置呢？

### ISSUE THREAD

**Issue by syt1998** [zjunlp/IEPile#32]
例如，对于文本“中国有五千年历史。”，其中词组“中国”为“国家”实体。输入文本后，期望模型能够以某种形式输出“国家”。
请问（1）在IEPILE上执行上述任务，instruction与output应该如何设置呢？（2）IEPILE是否适合执行上述任务？

**Comment by guihonghao** [comment]
你好，NER任务的instruction和output请参考

https://github.com/zjunlp/IEPile/blob/main/README_CN.md#22iepile%E7%9A%84%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F
