### ISSUE TITLE
请问在对领域内数据继续训练时，如果训练数据包含多个拥有不同schema的数据集，schema.json应如何设置？

### ISSUE THREAD

**Issue by syt1998** [zjunlp/IEPile#35]
例如我要在A、B这两个实体识别数据集上进行训练，其中A数据集的schema包括a、b、c、d、e这五种实体类型，A数据集的schema包括c、d、e、f、g、h这六种实体类型，那么schema.json中应如何体现[a, b, c, d, e]与[c, d, e, f, g, h]这两个不同的schema？

**Comment by guihonghao** [comment]
你可以设置两个目录A、B，目录A中的schema.json是[a, b, c, d, e]，目录B中的schema.json是[c, d, e, f, g, h]

**Comment by syt1998** [comment]
就是说，多个有不同schema数据集shuffle后组成的新数据集，是无法在当前IEPile的框架下训练的吗？

**Comment by guihonghao** [comment]
你好，我们训练用的数据集就是多个数据集混合成的。A数据集在A目录，B数据集在B目录。处理完所有数据集后再合并成混合数据集。
数据转换参考：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#41%E8%AE%AD%E7%BB%83%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%8D%A2

**Comment by syt1998** [comment]
明白了。
另外的问题是，（1）对于一条训练样本，是否只有"instruction"字段作为模型的输入且只有"output"字段用于loss计算？"task"与"source"字段的设置是否会对训练产生影响？（2）对于一条测试样本，是否只有"instruction"字段作为模型的输入？"id"、"task"与"source"字段的设置是否会对训练产生影响？

**Comment by syt1998** [comment]
明白了。
另外的问题是，（1）对于一条训练样本，是否只有"instruction"字段作为模型的输入且只有"output"字段用于loss计算？"task"与"source"字段的设置是否会对训练产生影响？（2）对于一条测试样本，是否只有"instruction"字段作为模型的输入？"id"、"task"与"source"字段的设置是否会对推理产生影响？

**Comment by guihonghao** [comment]
对于训练数据，只需要instruction、output字段，task、source只作统计使用。
测试数据需要"id"、"task"与"source"字段，在评估阶段需要使用。
"id"、"task"与"source"字段对于模型训练和推理没有任何影响。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
