### ISSUE TITLE
zero-shot inferencing

### ISSUE THREAD

**Issue by aivolcano** [zjunlp/IEPile#36]
Hi

I have some questions.
1. Is the prompt used for inferencing the same among GPT-4, ChatGPT, and LLaMA-2 in NER task? 
<img width="760" alt="image" src="https://github.com/user-attachments/assets/28288cf8-0cb8-4898-8bfc-27175d9519b0" />
2. If the prompts are indeed the same among those models, is the prompt template taken from the appendix?
<img width="726" alt="image" src="https://github.com/user-attachments/assets/907eadac-e7bb-43f8-bd34-d4846e92e6bc" />
3. To achieve the F1 score of 58.49 mentioned in Table 1, should I use the test dataset of CrossNER? Could u upload the code for GPT-4 in repo?

Thank u

**Comment by guihonghao** [comment]
Hello, we have adopted the instruction prompt used in IEPIPE but have further specified the return format. For NER, it is {"entity_type": ["entity"]}; for RE, it is {"head":"", "tail":"", "relation":""}; for EE, it is {"trigger": "", "event_type": "", "arguments": [{"argument": "", "role": ""}]}.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by aivolcano** [comment]
No, thank u some much
