### ISSUE TITLE
InstructIE数据集转化为SPO格式

### ISSUE THREAD

**Issue by l-besiege-l** [zjunlp/IEPile#5]
请问一下，我可以直接使用convert_func.py脚本，将InstructIE数据集转化为SPO格式的任务吗？我看代码里实际上是包含对SPO任务数据进行处理的，我在脚本里加了个模板就可以直接运行convert_func.py脚本
![image](https://github.com/zjunlp/IEPile/assets/52117792/0f221deb-2a07-4333-9c74-8e8051b54b10)

**Comment by guihonghao** [comment]
可以转换成SPO格式的任务，但是IEPILE模型是在RE格式的数据上训练的，因此对于SPO格式的任务效果可能不会太好（DuIE2.0从RE的75降到SPO上的55）。因此如果需要支持SPO格式的任务，还需要进行二次继续训练。

**Comment by l-besiege-l** [comment]
感谢大佬的回复，我准备使用生成的SPO数据微调模型，我看数据里生成的样本中，schema大多与input不太相关，导致样本的output很多都是空列表，请问这个负例的生成比例可以调整吗，显卡算力不太够想减少点样本量😂

**Comment by guihonghao** [comment]
https://github.com/zjunlp/IEPile/blob/main/README_CN.md#41%E8%AE%AD%E7%BB%83%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%8D%A2

我们更新了难负样本生成的代码，并上传了IEPILE中涉及的所有数据集的难负样本字典。
难负样本即那些处于相同主题、语义相近容易混淆的schema。通过难负样本生成可以有效减少样本量。
后续若样本量还是很大，还可以根据output进行下采样。

<img width="420" alt="image" src="https://github.com/zjunlp/IEPile/assets/53286894/cd56f24a-d7a0-46e8-aa1d-e79bc598a582">

**Comment by l-besiege-l** [comment]
好的，十分感谢

**Comment by vv521** [comment]
> 可以转换成SPO格式的任务，但是IEPILE模型是在RE格式的数据上训练的，因此对于SPO格式的任务效果可能不会太好（DuIE2.0从RE的75降到SPO上的55）。因此如果需要支持SPO格式的任务，还需要进行二次继续训练。

大佬您好，请问IEPILE和instructkgc两个项目中，哪个抽取模型对于spo抽取效果较好呀？
task支持直接设置spo进行微调训练吗？

**Comment by guihonghao** [comment]
两个项目中的模型均只考虑了RE任务，其中https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md支持在指令中增加schema解释，因此你可以尝试将SPO任务中的头、尾实体的解释加到schema解释中来实现。

**Comment by vv521** [comment]
> 将SPO任务中的头、尾实体类型的信息加到schema解释中来实现。
> 
> ```json
> {
> ```

好的感谢您，还想请教您一个问题：目前大模型的spo抽取效果是否没有传统实体关系联合抽取模型通过标注的效果佳呢？
