### ISSUE TITLE
求助，找不到文件夹

### ISSUE THREAD

**Issue by EternalSeer** [zjunlp/IEPile#8]
![gcCYIx3u1q](https://github.com/zjunlp/IEPile/assets/166979630/038824ce-d961-4936-9c18-627ca326af8d)
ls出现很奇怪的文件夹
![3yK3OVsxat](https://github.com/zjunlp/IEPile/assets/166979630/8a28f439-a42f-475d-9291-b67847d5cabd)

**Comment by EternalSeer** [comment]
![image](https://github.com/zjunlp/IEPile/assets/166979630/1727a3a1-d87d-44ab-b89e-0b54523cbd51)
这个是bash文件

**Comment by guihonghao** [comment]
你可以创建一个'lora/baichuan2-13b-chat-v1'的文件夹，去掉bash文件中的头两行，再把bash里面的--output_dir=${output_dir}改成--output_dir "lora/baichuan2-13b-chat-v1"试试。

**Comment by EternalSeer** [comment]
> 你可以创建一个'lora/baichuan2-13b-chat-v1'的文件夹，去掉bash文件中的头两行，再把bash里面的--output_dir=${output_dir}改成--output_dir "lora/baichuan2-13b-chat-v1"试试。

试过了，还是会报一样的错，很无语

**Comment by EternalSeer** [comment]
> 请问您的问题解决了吗

没有，太奇怪了

**Comment by EternalSeer** [comment]
> 请问您的问题解决了吗

![image](https://github.com/zjunlp/IEPile/assets/166979630/22bbb87c-2699-4e7d-8d4b-2b1a4446370f)
现在文件夹里是这样的

**Comment by guihonghao** [comment]
用绝对路径

**Comment by EternalSeer** [comment]
> 用绝对路径

关键文件夹已经手动创建了，看我上面的图片，然后还是报找不到文件夹的错

**Comment by guihonghao** [comment]
不是找不到文件夹，是识别不到你这条命令里面的--output_dir参数。--output_dir这一行也是红色的。检查前后是否多了空格。

**Comment by guihonghao** [comment]
![image](https://github.com/zjunlp/IEPile/assets/53286894/2e6f169d-8158-4db2-9e51-1eb264bf59aa)

**Comment by EternalSeer** [comment]
> ![image](https://private-user-images.githubusercontent.com/53286894/325207159-2e6f169d-8158-4db2-9e51-1eb264bf59aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjU1OTYsIm5iZiI6MTcxMzk2NTI5NiwicGF0aCI6Ii81MzI4Njg5NC8zMjUyMDcxNTktMmU2ZjE2OWQtODE1OC00ZGIyLTllNTEtMWViMjY0YmY1OWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzMjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYmI3YmRjOTVlNjUxMjliZDYzY2E3YmYyNjNiNzA1OGU3NGM4NzcyMzk3OTBkZWJhMGJmNDllMmQzYmIxZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2aTvwsVMbepa23LKt_m4O9bLzxnpKvosuHvVSvkI0AQ)

多谢大佬，解决了，真的是这个问题
