### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2788) of binary: /root/miniconda3/bin/python

### ISSUE THREAD

**Issue by EternalSeer** [zjunlp/IEPile#9]
![img_v3_02a9_f92cea47-7595-4d9e-8472-ccc84f0521fg](https://github.com/zjunlp/IEPile/assets/166979630/124db450-9066-4ece-ada6-b25d661e820a)
有哪个大佬遇到一样的错么?

**Comment by guihonghao** [comment]
看起来是模型下载的问题。

**Comment by EternalSeer** [comment]
> 看起来是模型下载的问题。

模型从modelscope下载的，好离谱。。

**Comment by guihonghao** [comment]
你好，modelscope上只有OneKE（基于llama2）的模型，看你的截图，你使用的是Baichuan模型。
OneKE的继续训练是：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#432lora%E8%AE%AD%E7%BB%83
OneKE的推理是：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#53ie%E4%B8%93%E7%94%A8%E6%A8%A1%E5%9E%8B%E9%A2%84%E6%B5%8B

**Comment by zxlzr** [comment]
请问您的问题是否已解决？

**Comment by EternalSeer** [comment]
> 你好，modelscope上只有OneKE（基于llama2）的模型，看你的截图，你使用的是Baichuan模型。 OneKE的继续训练是：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#432lora%E8%AE%AD%E7%BB%83 OneKE的推理是：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#53ie%E4%B8%93%E7%94%A8%E6%A8%A1%E5%9E%8B%E9%A2%84%E6%B5%8B

跑起来了，就是模型文件不完整导致的

**Comment by EternalSeer** [comment]
> 请问您的问题是否已解决？

还是报错了，在调试

**Comment by EternalSeer** [comment]
> 请问您的问题是否已解决？

已经解决了，重新下载了模型，换了训练集的大小就正常了，多谢大佬

**Comment by EternalSeer** [comment]
> 你好，modelscope上只有OneKE（基于llama2）的模型，看你的截图，你使用的是Baichuan模型。 OneKE的继续训练是：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#432lora%E8%AE%AD%E7%BB%83 OneKE的推理是：https://github.com/zjunlp/IEPile/blob/main/README_CN.md#53ie%E4%B8%93%E7%94%A8%E6%A8%A1%E5%9E%8B%E9%A2%84%E6%B5%8B

正常了，多谢大佬!
